import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar/Sidebar";
import { SessionProvider } from "next-auth/react";
import { SidebarRight } from "@/components/sidebarRight/SidebarRight";
import { auth } from "@/lib/auth";
import { Authentication } from "@/components/sidebar/Authentication";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  
  if(!session){
    return <html lang="en" className="bg-black text-white">
      <body className={"flex h-screen max-w-[1300px] gap-7 mx-auto " + inter.className}>
        <SessionProvider>
          <Authentication />
        </SessionProvider>
      </body>
    </html>
  }
  return (
    <html lang="en" className="bg-black text-white">
      <body className={"flex h-screen max-w-[1300px] gap-7 mx-auto " + inter.className}>
        <SessionProvider>
          <Sidebar />
          {children}
          <SidebarRight />
        </SessionProvider>
      </body>
    </html>
  );
}
